### ISSUE TITLE
GOAL: Automate AAA ingestion and calculation

### ISSUE THREAD

**Issue by Ivan-TRUF** [truflation/truflation#46] opened 2024-08-09 11:29 UTC
We need to scrape the AAA data daily and calculate AAA gasoilne and AAA Other fuels based on the following specs - https://docs.google.com/document/d/1kvTzZEHKAFb9dSb5J55NVzTsLjrWchfVdkYS7CFfNYA/edit

**Comment by markholdex** [comment] 2024-08-12 08:41
Duplicate of: https://github.com/truflation/truflation-ingestors/issues/14

**Closed** 2024-08-12 08:48 UTC
